Move JSON_CFLAGS before LIBPROXY_CFLAGS
Depending on build options, libproxy-1.0.pc depends indirectly
on json-c.pc:

libproxy-1.0 -> gio-2.0 -> mount -> libcryptsetup -> json-c

This causes "pkg-config --cflags libproxy-1.0" to emit
"-I/usr/include/json-c".

json-c installs a "json.h" file that conflicts with the one provided by
json-parser. If json-c comes before json-parser on the compiler command,
we get a build failure:

openconnect-internal.h:1654:59: error: unknown type name 'json_value'

[ dwmw2: This is a combination of at *least* three different bugs in
         three different packages conspiring to be my problem. See
         https://gitlab.com/openconnect/openconnect/-/merge_requests/476#note_1397129468
         But still, working around it does no harm for now.
         Ironically, if the presence of json-c on the include path
         wasn't *entirely* gratuitous then hiding it by putting it
         last wouldn't actually work because then something would
         fail to include the json-c version of <json.h> instead. ]

Bug: https://bugs.gentoo.org/906662
Signed-off-by: Mike Gilbert <floppym@gentoo.org>
Signed-off-by: David Woodhouse <dwmw2@infradead.org>